### PR TITLE
Make removing target work

### PR DESCRIPTION
**Pull request by ignatenkobrain**
GenericError: invalid type for id lookup: <type 'dict'>

Fixes: https://github.com/ktdreyer/koji-ansible/issues/128
Signed-off-by: Igor Raits <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
It would take me quite some time to write test for this because I'm not familiar with the framework, so please write it instead of me :)

Thanks!

**Comment by ktdreyer** [comment]
Thanks for this fix. Sure, I'll write some tests for this.

**Comment by ktdreyer** [comment]
In reviewing this code, we're not respecting `check_mode` when "state: absent". I would like to resolve https://github.com/ktdreyer/koji-ansible/issues/130 before we merge this one

**Comment by ignatenkobrain** [comment]
@ktdreyer ack, I'll fix it as part of this PR :)

**Comment by ignatenkobrain** [comment]
@ktdreyer pushed commit which fixes it too :)

**Comment by ktdreyer** [comment]
I've written some unit tests and an integration test for this, and it works. I'll submit those separately. Thank you!

**Comment by ktdreyer** [comment]
I've merged the unit tests in https://github.com/ktdreyer/koji-ansible/pull/133 and the integration test in https://github.com/ktdreyer/koji-ansible/pull/134 .

**Pull request merged**
