### PR TITLE
add RPM packaging

### PR DESCRIPTION
**Pull request by ktdreyer**
@tstellar asked if we could package this as an RPM, so here we go.

Add a spec file template and a Makefile for https://copr.fedorainfracloud.org/coprs/ktdreyer/koji-ansible/

### CODE REVIEW

**Comment by ktdreyer** [comment]
This is a work-in-progress as I get this building at https://copr.fedorainfracloud.org/coprs/ktdreyer/koji-ansible/builds/

**Comment by ignatenkobrain** [comment]
You probably should use RPM macro that I have created. Check ansible dist-git repo.

**Comment by ktdreyer** [comment]
Thanks for the pointer to the [Fedora ansible dist-git repo](https://src.fedoraproject.org/rpms/ansible). I tried using the macros there, and here is my feedback:

1. I generate the source `Source0` tarball with the [`./build-collection`](https://github.com/ktdreyer/koji-ansible/blob/master/build-collection) shell script. This script uses `ansible-galaxy collection build` to assemble the tarball. Unfortunately this tarball does not include the `galaxy.yml` file. This means that if I unpack the tarball in `%prep` and then try to "rebuild" the collection during `%build` (with `%ansible_collection_build`), `ansible-galaxy` complains that there is no `galaxy.yml` file.

2. The `%ansible_collection_files` macro captures the whole parent `%{collection_namespace}` directory rather than `%{collection_namespace}/%{collection_name}`. I think this is a bug to fix in `macros.ansible`.

3. It was not clear to me how to use the stuff in [ansible.attr](https://src.fedoraproject.org/rpms/ansible/c/db3f8ce6dcb8907cf9e5e06ee399a18c6696887a). Am I supposed to use some or all of those?

4. It would be great to put these macros into EPEL 8 eventually

**Comment by ktdreyer** [comment]
On Rawhide I can do the following:

```
dnf install 'dnf-command(copr)'
dnf copr enable ktdreyer/koji-ansible
dnf install ansible-collection-ktdreyer-koji-ansible
```

And I can read the docs like so:
```
ansible-doc -t module ktdreyer.koji_ansible.koji_tag
```

**Comment by ktdreyer** [comment]
I'm going to merge this for now and see how it goes. We'll just build for Rawhide and EPEL 8 for now.

**Pull request merged**
